server:
  port: 8090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
logging:
  level:
    dev:
      samagua:
        ekumen_tourism_tracker_backend: DEBUG